version: "3.9"

services:
  backend:
    build: ../backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  # 🚀 Attendre que la BDD soit prête
      redis:
        condition: service_started
    environment:
      - DATABASE_URL=dbname=quotes_db user=postgres password=password host=db port=5432
      - REDIS_HOST=redis

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: quotes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:  # ✅ Attendre que PostgreSQL soit opérationnel
      test: ["CMD-SHELL", "pg_isready -U postgres -d quotes_db"]
      interval: 5s
      retries: 5
      timeout: 3s

  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
